### ISSUE TITLE
VAL_TABLE_ cannot be parsed

### ISSUE THREAD

**Issue by theryangeary** [marcelbuesing/can-dbc#5]
Hi there,
I am trying to parse a `VAL_TABLE_`. I have added it to the `SAMPLE_DBC` in `lib.rs`, right after the `VAL_` line, and it looks like this:

```
VAL_TABLE_ Signal_4 1 \"Val1\" 2 \"Val2\";
```

This results in an `Incomplete` error. Am I doing something wrong? I've tried several variants of VAL_TABLE_ lines, and nothing seems to work.

**Comment by theryangeary** [comment]
It appears the issue is resolved when I add a space preceding the `;`. I am guessing this may be part of the DBC format requirements? I will leave the issue open and allow you to decide whether or not this is a real issue.

**Comment by marcelbuesing** [comment]
Hi, thanks for this. The document I found when googling regarding the dbc structure is not really clear about white space. So I think it probably makes to be lenient here and accept it also without a space. Thanks for finding this. If you need a quick bug fix release containing this let me know.
